### ISSUE TITLE
Error at Karma node_module after gulp serve

### ISSUE THREAD

**Issue by ramicodes** [ytechie/AzureResourceVisualizer#31]
D:\Code\GitHub\AzureResourceVisualizer>gulp serve
D:\Code\GitHub\AzureResourceVisualizer\node_modules\karma\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (D:\Code\GitHub\AzureResourceVisualizer\node_modules\karma\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Code\GitHub\AzureResourceVisualizer\node_modules\karma\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:635:30)

D:\Code\GitHub\AzureResourceVisualizer>

**Comment by ytechie** [comment]
This is the legacy version. Want to try the 2.0 version? https://github.com/shenglol/arm-visualizer
